-- Execute conectado ao banco postgres como superusuario: psql -U postgres -d postgres -f scripts/01_setup_database.sql
CREATE DATABASE movimentador_contas WITH ENCODING 'UTF8';
\connect movimentador_contas
REVOKE ALL ON DATABASE movimentador_contas FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA workflow;
CREATE SCHEMA audit;
REVOKE ALL ON SCHEMA workflow, audit FROM PUBLIC;

CREATE TABLE workflow.setores (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(100) NOT NULL UNIQUE,
 ativo boolean NOT NULL DEFAULT true
);
CREATE TABLE workflow.usuarios (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 login_corporativo varchar(80) NOT NULL UNIQUE,
 nome_completo varchar(160) NOT NULL,
 setor_id bigint NOT NULL REFERENCES workflow.setores(id),
 credencial_hash text NOT NULL,
 perfil_acesso varchar(30) NOT NULL CHECK (perfil_acesso IN ('operacional','gestao','admin'))
);
-- A credencial_hash demonstra proteção de coluna; autenticação real é feita pelas roles PostgreSQL.
CREATE TABLE workflow.contas_workflow (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo_fatura varchar(40) NOT NULL UNIQUE,
 convenio varchar(100) NOT NULL,
 valor_aproximado numeric(12,2) NOT NULL CHECK (valor_aproximado >= 0),
 setor_atual_id bigint NOT NULL REFERENCES workflow.setores(id),
 data_entrada timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE workflow.movimentacoes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conta_id bigint NOT NULL REFERENCES workflow.contas_workflow(id),
 setor_origem_id bigint NOT NULL REFERENCES workflow.setores(id),
 setor_destino_id bigint NOT NULL REFERENCES workflow.setores(id),
 usuario_executor_id bigint NOT NULL REFERENCES workflow.usuarios(id),
 ocorrido_em timestamptz NOT NULL DEFAULT clock_timestamp(),
 observacao text NOT NULL CHECK (length(btrim(observacao)) > 0),
 CONSTRAINT setores_distintos CHECK (setor_origem_id <> setor_destino_id)
);
CREATE INDEX movimentacoes_conta_tempo_idx ON workflow.movimentacoes(conta_id, ocorrido_em DESC, id DESC);
CREATE TABLE workflow.comentarios (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conta_id bigint NOT NULL REFERENCES workflow.contas_workflow(id),
 usuario_autor_id bigint NOT NULL REFERENCES workflow.usuarios(id),
 criado_em timestamptz NOT NULL DEFAULT clock_timestamp(),
 descricao text NOT NULL CHECK (length(btrim(descricao)) > 0)
);
CREATE INDEX comentarios_conta_tempo_idx ON workflow.comentarios(conta_id, criado_em DESC);
